import type { ModelDefinition } from '../kie/types.ts'

export const DEDICATED_MODELS: ModelDefinition[] = [
  {
    id: 'suno/music',
    model: 'suno/music',
    title: 'Suno — 楽曲を作る',
    category: 'audio',
    provider: 'suno',
    operation: 'generate',
    useCase: '楽曲',
    tags: ['music', 'lyrics', 'instrumental'],
    docsUrl: 'https://docs.kie.ai/suno-api/generate-music',
    fields: [
      { name: 'customMode', type: 'boolean', label: '歌詞・スタイルを指定', default: true },
      { name: 'instrumental', type: 'boolean', label: 'インストゥルメンタル', default: false },
      { name: 'prompt', type: 'textarea', label: '歌詞 / 作りたい曲', maxLength: 5000 },
      { name: 'style', type: 'textarea', label: 'スタイル', description: 'ジャンル、テンポ、楽器、声質など', maxLength: 1000 },
      { name: 'title', type: 'string', label: 'タイトル', maxLength: 100 },
      { name: 'model', type: 'enum', label: 'Sunoモデル', enum: ['V5', 'V4_5PLUS', 'V4_5', 'V4'], default: 'V5' },
      { name: 'negativeTags', type: 'string', label: '避けたい要素', maxLength: 500 },
      { name: 'personaId', type: 'string', label: 'Persona ID', description: '素材棚のPersonaを選ぶと自動入力されます' },
    ],
  },
  {
    id: 'suno/extend',
    model: 'suno/extend',
    title: 'Suno — 曲の続きを作る',
    category: 'audio',
    provider: 'suno',
    operation: 'extend',
    useCase: '楽曲',
    tags: ['music', 'extend'],
    fields: [
      { name: 'taskId', type: 'string', label: '元タスクID', required: true },
      { name: 'audioId', type: 'string', label: '元Audio ID', required: true },
      { name: 'continueAt', type: 'number', label: '続ける位置（秒）', required: true, min: 0, step: 0.1 },
      { name: 'prompt', type: 'textarea', label: '続きの歌詞 / 指示', required: true },
      { name: 'style', type: 'string', label: 'スタイル' },
      { name: 'title', type: 'string', label: 'タイトル' },
      { name: 'model', type: 'enum', label: 'Sunoモデル', enum: ['V5', 'V4_5PLUS', 'V4_5', 'V4'], default: 'V5' },
    ],
  },
  {
    id: 'suno/upload-extend',
    model: 'suno/upload-extend',
    title: 'Suno — 外部音源の続きを作る',
    category: 'audio',
    provider: 'suno',
    operation: 'upload-extend',
    useCase: '楽曲',
    tags: ['music', 'upload', 'extend'],
    fields: [
      { name: 'uploadUrl', type: 'reference', label: '音源', required: true, accept: 'audio/*', scalar: true, mentionStyle: 'none', maxItems: 1, maxDurationSec: 480 },
      { name: 'continueAt', type: 'number', label: '続ける位置（秒）', required: true, min: 0, max: 480, step: 0.1 },
      { name: 'prompt', type: 'textarea', label: '続きの歌詞 / 指示', required: true },
      { name: 'style', type: 'string', label: 'スタイル' },
      { name: 'title', type: 'string', label: 'タイトル' },
      { name: 'model', type: 'enum', label: 'Sunoモデル', enum: ['V5', 'V4_5PLUS', 'V4_5', 'V4'], default: 'V5' },
    ],
  },
  {
    id: 'suno/upload-cover',
    model: 'suno/upload-cover',
    title: 'Suno — 音源をカバーする',
    category: 'audio',
    provider: 'suno',
    operation: 'upload-cover',
    useCase: '楽曲',
    tags: ['music', 'upload', 'cover'],
    docsUrl: 'https://docs.kie.ai/suno-api/upload-and-cover-audio',
    fields: [
      { name: 'uploadUrl', type: 'reference', label: '元の音源', required: true, accept: 'audio/*', scalar: true, mentionStyle: 'none', maxItems: 1, maxDurationSec: 480 },
      { name: 'customMode', type: 'boolean', label: '歌詞・スタイルを指定', default: true },
      { name: 'instrumental', type: 'boolean', label: 'インストゥルメンタル', default: false },
      { name: 'prompt', type: 'textarea', label: '歌詞 / カバーの指示', maxLength: 5000 },
      { name: 'style', type: 'textarea', label: 'スタイル', maxLength: 1000 },
      { name: 'title', type: 'string', label: 'タイトル', maxLength: 100 },
      { name: 'model', type: 'enum', label: 'Sunoモデル', enum: ['V5', 'V4_5PLUS', 'V4_5', 'V4'], default: 'V5' },
    ],
  },
  {
    id: 'suno/lyrics',
    model: 'suno/lyrics',
    title: 'Suno — 歌詞を作る',
    category: 'audio',
    provider: 'suno',
    operation: 'lyrics',
    useCase: '楽曲',
    tags: ['music', 'lyrics', 'writing'],
    docsUrl: 'https://docs.kie.ai/suno-api/generate-lyrics',
    fields: [
      { name: 'prompt', type: 'textarea', label: '歌詞のテーマ / 指示', required: true, maxLength: 2000 },
    ],
  },
  {
    id: 'suno/replace-section',
    model: 'suno/replace-section',
    title: 'Suno — 区間だけ作り直す',
    category: 'audio',
    provider: 'suno',
    operation: 'replace-section',
    useCase: '楽曲',
    tags: ['music', 'edit'],
    fields: [
      { name: 'taskId', type: 'string', label: '元タスクID', required: true },
      { name: 'audioId', type: 'string', label: '元Audio ID', required: true },
      { name: 'infillStartS', type: 'number', label: '開始（秒）', required: true, min: 0, step: 0.1 },
      { name: 'infillEndS', type: 'number', label: '終了（秒）', required: true, min: 6, step: 0.1 },
      { name: 'prompt', type: 'textarea', label: '置換する歌詞 / 内容', required: true },
      { name: 'tags', type: 'string', label: 'スタイル', required: true },
      { name: 'title', type: 'string', label: 'タイトル', required: true },
      { name: 'negativeTags', type: 'string', label: '避けたい要素' },
      { name: 'fullLyrics', type: 'textarea', label: '全歌詞（任意）' },
      { name: '_duration', type: 'number', label: '元音源の長さ（検証用）', min: 0 },
    ],
  },
  {
    id: 'market/elevenlabs-dialogue',
    model: 'elevenlabs/text-to-dialogue-v3',
    title: 'ElevenLabs — 会話を作る',
    category: 'audio',
    provider: 'market',
    operation: 'generate',
    useCase: '会話',
    tags: ['speech', 'dialogue'],
    docsUrl: 'https://docs.kie.ai/market/elevenlabs/text-to-dialogue-v3',
    fields: [
      { name: 'dialogue', type: 'json', label: '話者行', required: true, description: '[{"text":"こんにちは","voice":"voice-id"}]' },
      { name: 'stability', type: 'number', label: '声の安定性', min: 0, max: 1, step: 0.5, default: 0.5 },
      { name: 'language_code', type: 'string', label: '言語コード', description: '例: ja。空欄なら自動判定' },
    ],
  },
  {
    id: 'market/elevenlabs-tts',
    model: 'elevenlabs/text-to-speech-multilingual-v2',
    title: 'ElevenLabs — ナレーション',
    category: 'audio',
    provider: 'market',
    operation: 'generate',
    useCase: 'ナレーション',
    tags: ['speech', 'tts', 'multilingual'],
    docsUrl: 'https://docs.kie.ai/market/elevenlabs/text-to-speech-multilingual-v2',
    fields: [
      { name: 'text', type: 'textarea', label: '原稿', required: true, maxLength: 20000, description: '空行で最大5000文字ずつのセグメントに分けます' },
      { name: 'voice', type: 'string', label: 'Voice ID', required: true },
      { name: 'stability', type: 'number', label: '声の安定性', min: 0, max: 1, step: 0.05, default: 0.5 },
      { name: 'similarity_boost', type: 'number', label: '声の類似度', min: 0, max: 1, step: 0.05, default: 0.75 },
      { name: 'style', type: 'number', label: '表現の強さ', min: 0, max: 1, step: 0.05, default: 0 },
      { name: 'speed', type: 'number', label: '話速', min: 0.7, max: 1.2, step: 0.05, default: 1 },
      { name: 'timestamps', type: 'boolean', label: '単語タイムスタンプ', default: true },
      { name: 'previous_text', type: 'textarea', label: '前の文脈', description: 'セグメント生成時は自動接続されます', maxLength: 5000 },
      { name: 'next_text', type: 'textarea', label: '次の文脈', description: 'セグメント生成時は自動接続されます', maxLength: 5000 },
      { name: 'language_code', type: 'string', label: '言語コード', description: '例: ja。空欄なら自動判定' },
    ],
  },
  {
    id: 'veo/generate',
    model: 'veo',
    title: 'Veo — 映像を作る',
    category: 'video',
    provider: 'veo',
    operation: 'generate',
    useCase: '映像生成',
    tags: ['veo', 'video'],
    fields: [
      { name: 'prompt', type: 'textarea', label: '映像の指示', required: true },
      { name: 'imageUrls', type: 'reference', label: '参照画像', accept: 'image/*', maxItems: 3, mentionStyle: 'none' },
      { name: 'model', type: 'enum', label: 'Veoモデル', enum: ['veo3_fast', 'veo3'], default: 'veo3_fast' },
      { name: 'aspectRatio', type: 'enum', label: '比率', enum: ['16:9', '9:16'], default: '16:9' },
    ],
  },
  {
    id: 'veo/extend',
    model: 'veo/extend',
    title: 'Veo — 映像を延長',
    category: 'video',
    provider: 'veo',
    operation: 'extend',
    useCase: '映像編集',
    tags: ['veo', 'extend'],
    fields: [
      { name: 'taskId', type: 'string', label: '元タスクID', required: true },
      { name: 'prompt', type: 'textarea', label: '続きの指示', required: true },
    ],
  },
  {
    id: 'veo/1080p',
    model: 'veo/1080p',
    title: 'Veo — 1080pに変換',
    category: 'video',
    provider: 'veo',
    operation: 'upscale-1080p',
    useCase: '高画質化',
    tags: ['veo', '1080p', 'upscale'],
    fields: [
      { name: 'taskId', type: 'string', label: '元タスクID', required: true },
      { name: 'index', type: 'number', label: '動画番号', required: true, min: 0, max: 3, step: 1, default: 0 },
    ],
  },
  {
    id: 'veo/4k',
    model: 'veo/4k',
    title: 'Veo — 4Kに変換',
    category: 'video',
    provider: 'veo',
    operation: 'upscale-4k',
    useCase: '高画質化',
    tags: ['veo', '4k', 'upscale'],
    fields: [
      { name: 'taskId', type: 'string', label: '元タスクID', required: true },
      { name: 'index', type: 'number', label: '動画番号', required: true, min: 0, max: 3, step: 1, default: 0 },
    ],
  },
  {
    id: 'runway/generate',
    model: 'runway',
    title: 'Runway — 映像を作る',
    category: 'video',
    provider: 'runway',
    operation: 'generate',
    useCase: '映像生成',
    tags: ['runway', 'video'],
    fields: [
      { name: 'prompt', type: 'textarea', label: '映像の指示', required: true },
      { name: 'imageUrl', type: 'reference', label: '開始画像', accept: 'image/*', scalar: true, maxItems: 1, mentionStyle: 'none' },
      { name: 'duration', type: 'enum', label: '長さ', enum: ['5', '10'], default: '5' },
      { name: 'quality', type: 'enum', label: '画質', enum: ['720p', '1080p'], default: '720p' },
      { name: 'aspectRatio', type: 'enum', label: '比率', enum: ['16:9', '9:16', '1:1'], default: '16:9' },
    ],
  },
  {
    id: 'runway/extend',
    model: 'runway/extend',
    title: 'Runway — 映像を延長',
    category: 'video',
    provider: 'runway',
    operation: 'extend',
    useCase: '映像編集',
    tags: ['runway', 'extend'],
    fields: [
      { name: 'taskId', type: 'string', label: '元タスクID', required: true },
      { name: 'videoId', type: 'string', label: '元Video ID', required: true },
      { name: 'prompt', type: 'textarea', label: '続きの指示', required: true },
    ],
  },
  {
    id: 'runway/aleph',
    model: 'runway/aleph',
    title: 'Runway Aleph — 映像を変える',
    category: 'video',
    provider: 'runway',
    operation: 'aleph',
    useCase: '映像編集',
    tags: ['runway', 'aleph', 'edit'],
    docsUrl: 'https://docs.kie.ai/runway-api/generate-aleph-video',
    fields: [
      { name: '_parentTaskId', type: 'string', label: '親タスクID' },
      { name: 'videoUrl', type: 'reference', label: '元動画', required: true, accept: 'video/*', scalar: true, maxItems: 1, mentionStyle: 'none' },
      { name: 'prompt', type: 'textarea', label: '変えたい内容', required: true },
    ],
  },
  {
    id: 'market/volcengine-lip-sync',
    model: 'volcengine/video-to-video-lip-sync',
    title: 'Volcengine — 動画をリップシンク',
    category: 'video',
    provider: 'market',
    operation: 'generate',
    useCase: 'リップシンク',
    tags: ['video', 'audio', 'lip-sync'],
    docsUrl: 'https://docs.kie.ai/market/volcengine/video-to-video-lip-sync',
    fields: [
      { name: 'video_url', type: 'reference', label: '動画', required: true, accept: 'video/*', scalar: true, maxItems: 1, mentionStyle: 'none' },
      { name: 'audio_url', type: 'reference', label: '音声', required: true, accept: 'audio/*', scalar: true, maxItems: 1, mentionStyle: 'none' },
    ],
  },
]
